version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  productapi:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      # DatabaseSettings:ConnectionString o valor dele eh substituido do appsettings e o catalogdb eh o nome do container
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
